version: "3.8"
services:
  frontend:
    build: ./front
    ports:
      - "80:80"
     
    depends_on:
      - backend

  backend:
    build: ./back
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    depends_on:
      - db  

  db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
