apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2   # 2 pods backend (scalabilité)
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: louayabidi/myapp-back:latest   # image DockerHub
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://admin:adminpassword@mongo-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
