apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2   # 2 pods frontend
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: louayabidi/myapp-front:latest   # image DockerHub
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer   # expose au monde extérieur
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
