name: Build & Push Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp-back:latest,${{ secrets.DOCKERHUB_USERNAME }}/myapp-back:${{ github.ref_name }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp-front:latest,${{ secrets.DOCKERHUB_USERNAME }}/myapp-front:${{ github.ref_name }}
